"""Initial schema

Revision ID: 6e24cf971422
Revises:
Create Date: 2021-10-02 18:38:42.405585

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "6e24cf971422"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("comment", sa.String(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entries")
    # ### end Alembic commands ###
