name: "test-pipeline"

on:
  push:
    branches:
    - '*'

jobs:
  pre-release:
    name: "Test pipeline"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v2
    # here decide which version will be used if it is nto release
    - name: Set env vars
      run: |
        echo "CREATED=`date -u +"%Y-%m-%dT%H:%M:%SZ"`" >> $GITHUB_ENV
        echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "VCS_REF=${GITHUB_SHA}" >> $GITHUB_ENV
    - name: Test env vars
      run: |
        echo ${{ env.CREATED }}
        echo ${{ env.VERSION }}
        echo ${{ env.VCS_REF }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          jakuboskera/guestbook:test-pipeline
        build-args: |
          CREATED=${{ env.CREATED }}
          VERSION=${{ env.VERSION }}
          VCS_REF=${{ env.VCS_REF }}

